### ISSUE TITLE
olevba fails to convert Chr() funtions that add a negative number

### ISSUE THREAD

**Issue by w3tmo** [decalage2/oletools#122]
Olevba fails to convert Chr() functions that add a negative number. 

For example:
It will convert Chr(69 + 28) to the proper character, however it fails to convert Chr(-81 + 189) as well as Chr(51 + -6) to the correct character. It seems to skip every Chr call that involves a negative number. I am using the --reveal switch.

**Comment by decalage2** [comment]
TODO: test after PR #127

**Comment by decalage2** [comment]
I tested PR #127 using the following files: 

[oletools_issue_122.zip](https://github.com/decalage2/oletools/files/1062443/oletools_issue_122.zip)

The issue was not solved, but I found the solution with commit 2ed0a9b
