### ISSUE TITLE
XML word document with VBA macros not parsed correctly

### ISSUE THREAD

**Issue by gregcopenhaver** [decalage2/oletools#169]
When using olevba with this sample, it does not detect any of the Office formats and treats it as a plain text file.

SHA256: a5fd22029110e5c42dc4136bf8e31435ee7a55639da07020721ea19f71e24a78

When manually extracting and decoding the vbaProject.bin file, olevba handles it without any problems.

olevba checks for the "http://schemas.microsoft.com/office/word/2003/wordml" schema, but this sample has the year 2006 rather than 2003. I'm not sure if this is yet another format, or just a newer version of the 2003 XML format.

**Comment by gregcopenhaver** [comment]
I see this being referred to as "The Flat OPC Format" here:
https://blogs.msdn.microsoft.com/ericwhite/2008/09/29/the-flat-opc-format/

**Comment by decalage2** [comment]
same as #283, should be addressed in latest dev version 0.53dev4

**Comment by christian-intra2net** [comment]
I have tried to detect such documents in ooxml.py, using it in msodde.py. Lacking a proper name for it, referred to it as "single-xml" files.

**Comment by decalage2** [comment]
It does not seem to be well documented. On the old blog posts about it, the format is named "Flat OPC". (OPC = Open Packaging Convention, the container structure for OpenXML). But in MS Word and PowerPoint, it is simply named "Word XML" or "PowerPoint XML", as opposed to "Word 2003 XML" for the older XML version. I chose to name it "Word 2007+ XML" to be more explicit.

**Comment by decalage2** [comment]
Fixed for olevba and olevba3, see #283.
