### ISSUE TITLE
Virtualenv-installed olebrowse broken

### ISSUE THREAD

**Issue by Flameeyes** [decalage2/oletools#174]
When installing oletools wth `pip` on a `virtualenv`, the `olebrowse` binary tries to import from `thirdparty` as if it was in the Python load path, when it's not:

```
Traceback (most recent call last):
  File "/home/flame/usblyzer-tests/bin/olebrowse", line 7, in <module>
    from oletools.olebrowse import main
  File "/home/flame/usblyzer-tests/lib/python3.4/site-packages/oletools/olebrowse.py", line 55, in <module>
    from thirdparty.easygui import easygui
ImportError: No module named 'thirdparty'
```

**Comment by decalage2** [comment]
Hi, did you use the latest version from the repo? (normally this issue should have been fixed)

See https://github.com/decalage2/oletools/wiki/Install#how-to-install-the-latest-development-version

**Comment by Flameeyes** [comment]
No I have used the current, pip-installed release. Any hope for a new release if this is fixed?

**Comment by decalage2** [comment]
Hi @Flameeyes, the new version 0.51 is now on PyPI: could you please check again after updating with `pip install -U oletools` ? Thanks.

**Comment by decalage2** [comment]
I assume it works now.
