### ISSUE TITLE
olevba - Edit vbaproject.bin

### ISSUE THREAD

**Issue by gonik** [decalage2/oletools#175]
Hello @decalage2.

I can't say enough how useful the `oletools` well... tools are! You have done a truly fantastic job.

I was wondering whether it could be possible to add the functionality to edit the vbaproject.bin in addition to "read" it. The reason is that in our team we have developed some Excel workbooks, to help us with our projects.
Each tool require some modification of the original sheet, depending on various factors. I am trying to automate the process as much as possible by writing batch scripts which allow me to edit the rest of XMLs in the file, but as you can imagine I haven't figured out a way to edit the OLE `VBAProject.bin` file.

Or maybe point me in the right direction of a third program which allow me to actually dumb all the sub routines to a text file, edit it and then somehow recompile it back to `.bin` without the need to open up Excel.

I realize that this maybe a strange request and somehow outside of the scope of `oletools`, but I really appreciate your excellent work so far!

Best,
gonik

**Comment by decalage2** [comment]
Hello @gonik, indeed it would be great to be able to modify the source code of VBA macros using oletools. However, this is not possible for now, and a lot of work would be needed:

1. For now, olefile can only write data into streams without changing their size. So the VBA source code cannot be larger than the original. (see https://github.com/decalage2/olefile/issues/6)
1. The VBA source code is compressed into a stream of vbaproject.bin. The algorithms to compress and decompress the code are specified in [MS-OVBA section 2.4.1](https://msdn.microsoft.com/en-us/library/dd923471(v=office.12).aspx). For now, only the decompression is implemented in olevba. Someone would need to develop the compression algorithm in python.
1. A VBA project also contains a pre-compiled version of the VBA code (kind of bytecode). When the VBA engine version matches the one which compiled the code, then it will run that bytecode directly, without looking at the source code. So if you modify the source code, you also need to remove the bytecode to avoid issues. (see https://github.com/bontchev/pcodedmp for more info)

**Comment by gonik** [comment]
Wow, I really appriciate your answer. Very detailed!
I realized that this would require much work but I didn't realize the exact load.

Thank you very much for the time you took to answer this. Keep up the great work you've done so far.

Best,
gonik

**Comment by decalage2** [comment]
Thanks for the nice words. :-)
