### ISSUE TITLE
olevba.py/olevba3.py call sys.exit instead of raising an exception

### ISSUE THREAD

**Issue by chehsunliu** [decalage2/oletools#180]
One of my scripts retrieves VB macros from lots of files including non-office files. I caught and passed those exceptions caused by non-office files to filter them. Sometimes my script terminated without any logs though a try-except block for `Exception` wrapped the whole scope.

Finally, we found the trigger point on the line 1546 and 1547 in `olevba3.py`, 
```python
log.error('invalid or unknown check Id {0:04X}'.format(check))
sys.exit(0)
```

Why is it necessary to call `sys.exit(0)` instead of just raising an exception?

**Comment by chehsunliu** [comment]
By the way, the file triggering this behavior is an Excel file written in Japanese. Enabling macros when opening the file will pop up an error message "Compile error: Invalid character."

**Comment by decalage2** [comment]
Hi @chehsunliu, I replaced sys.exit by an exception in olevba (not olevba3 yet). Could you please check if it solves the issue with your file?

And could you please tell me the hash of the file, if it is available on VT or other? Thanks.

**Comment by chehsunliu** [comment]
I checked VT and the sample isn't available on it. I cannot provide it due to customer privacy.

My production code is using Python 3.6 and I hadn't tested the sample under Python 2.7. However, I just tested the sample and found it ran well under Python 2.7 without this patch. You got misled by my comments. My apologies...

**Comment by decalage2** [comment]
looks like it was already fixed, closed.
