### ISSUE TITLE
.doc in msodde.py

### ISSUE THREAD

**Issue by christian-intra2net** [decalage2/oletools#203]
Just to let you know: I am working on extending the new msodde.py (thanks so much for this!) to also find dde-links in older .doc files. Also added json-formatted output. Will send you a pull request next week.

I noticed that there is a pull-request for including unit tests ( #201 ). I love those! Would be great to have them in oletools :-)

**Comment by decalage2** [comment]
That's great! I was also planning to look at legacy doc files, but if you find a good way to do it, be my guest. :-) (for now I have just seen the DDE and DDEAUTO keywords appear in clear text, but there must be a cleaner way to extract the full DDE string with arguments)

I just merged PR #201 to add unit tests.

**Comment by christian-intra2net** [comment]
Great, thanks a lot!
