### ISSUE TITLE
msodde: finds much more than dde

### ISSUE THREAD

**Issue by christian-intra2net** [decalage2/oletools#214]
In the current version the output of msodde.py is not always what its name suggests (namely, DDE links) . The rules finding "instrText" in OpenXML-Documents capture much more than just DDE links. I have seen examples where such fields are used for page numbering, creation of table-of-contents, etc. msodde.py reports these as "dde links" although they are, in fact, harmless page numbers.

On http://officeopenxml.com/WPfieldInstructions.php there is a list of instructions that can appear, which seems to be incomplete (does not mention DDE nor DDEAUTO). Many instructions there seem harmless (like PAGE or DATE or USER). Other field instructions (e.g. HYPERLINK) can carry harmful content, so finding and returning them would make sense.

As a partial solution I suggest adding a whitelist of harmless instructions that may appear in instrText fields that will then not be reported by msodde.py.

In the longer run one could think about renaming msodde.py or really restricting it to dde[auto] and offering other tools to find other potentially malicious content in instrText fields.

**Comment by decalage2** [comment]
You're right, it was my plan to display only DDE related fields by default, with an option to display all of them. I just haven't done it yet.

**Comment by christian-intra2net** [comment]
then what about I create a pull request with a new command line argument and 3 options
- show all
- show only dde / ddeauto
- show all except harmless (with my proposed whitelist)
?

**Comment by christian-intra2net** [comment]
then what about I create a pull request with a new command line argument and 3 options
- show all
- show only dde / ddeauto
- show all except harmless (with my proposed whitelist)
?

**Comment by decalage2** [comment]
Good idea. I think the default behaviour should be to show DDE fields, and the other fields that you mentioned which could be misused (also INCLUDE, as shown in https://twitter.com/SecuritySift/status/928669411384483840). Show all and show only DDE* would be options.

**Comment by decalage2** [comment]
Side note: I'm not fully happy with the name "msodde", but that's the one that came up. It could be renamed "msofields" or something else before I release the new oletools version on PyPI.

**Comment by christian-intra2net** [comment]
I fully agree.

On a side note: after having studied the openxml-specs to create a good blacklist parser (it is only 5000 or so pages :-) ) I found the DDE and DDEAUTO are nowhere to be found in that standard nor in the document that specifies microsoft's extension to it.

**Comment by christian-intra2net** [comment]
Created pull request #216

**Comment by samiraguiar** [comment]
I've found these two reference documents that might help (both mention DDEAuto and more):
[WdLinkType Enumeration](https://msdn.microsoft.com/en-us/VBA/Word-VBA/articles/wdlinktype-enumeration-word)
[WdFieldType Enumeration](https://msdn.microsoft.com/en-us/library/microsoft.office.interop.word.wdfieldtype.aspx)
