### ISSUE TITLE
oletools v0.52 failed to install on Windows 10

### ISSUE THREAD

**Issue by Dripdrop12** [decalage2/oletools#265]
`pip install -U oletools` results in a fatal error on setup.py. I downloaded v0.51 and it was able to install just fine!

**Comment by decalage2** [comment]
Hi, thanks for the report. Could you please provide the full error message, and tell me which python version you are using ? 

Also, does your username or the python path contain any Unicode character ? Thanks.

**Comment by Dripdrop12** [comment]
Python Version 3.6.4, the default installation was C:\users\username\appdata\local\programs\python\python36-32.

Since I was able to resolve the issue by walking back one version of oletools, I don't have the full error message anymore :(

**Comment by ed-turner** [comment]
I received the same error.  This is it.

(base) C:\Users\user_name>pip install -U oletools
Collecting oletools
  Using cached oletools-0.52.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user_name\AppData\Local\Temp\pip-build-8j4gzv40\oletools\setup.py", line 47, in <module>
        long_desc    = open('oletools/README.rst').read()
      File "C:\Users\user_name\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 8384: character maps to <undefined>

**Comment by Chrisly3ear** [comment]
I have teh same problem on Windows 10 using Python 3.6.4

**Comment by decalage2** [comment]
I see, we had the exact same issue with olefile (https://github.com/decalage2/olefile/pull/89), this is due to special quote characters inserted by pandoc in the readme file, when converting from markdown to rst... I'll fix it soon and publish a new release on pypi.

**Comment by decalage2** [comment]
fixed by commit 9a890da1825bd6a16bab9a40c2388a445f79ad8a
