### ISSUE TITLE
oleobj.py - off-by-one error

### ISSUE THREAD

**Issue by omg1337** [decalage2/oletools#274]
261    else:
262        ansi_string = data[index:index+length-1]
263        null_char = data[index+length]

null-char should be data[index+length-1]

Embedded Objects successfully parse now because "next fields SHOULD contain an empty string" (2.2.4 ObjectHeader)

**Comment by decalage2** [comment]
Do you have any samples of OleLink so that I can test it? Thanks @omg1337.

**Comment by omg1337** [comment]
You can craft it yourself )
https://support.office.com/en-us/article/Insert-an-object-in-Word-or-Outlook-8fc1ea53-0e01-4603-a4cf-98c49b6ea3f5

**Comment by decalage2** [comment]
Thanks, I managed to test it and the fix works well.
