### ISSUE TITLE
accdb extract ole object (picturedata)

### ISSUE THREAD

**Issue by paulopires16** [decalage2/oletools#278]
Is it possible extract images from axxdb with this tool? Convert to PIL and then save on disc?

**Comment by decalage2** [comment]
Do you have a sample file?

**Comment by paulopires16** [comment]
Thanks Philippe,
Yes I have
[https://ufile.io/5wkgd](url)

**Comment by decalage2** [comment]
From what I have read, the MS Access .accdb format is not documented, and it is different from all the other MS Office formats. I did not find any solution to parse accdb with Python. So no, sorry, you can't use oletools with MS Access files. :-(

**Comment by paulopires16** [comment]
my variable[:100] after read images, see image link please:

https://imgur.com/q2Z4nEo

eatch row is one image... this is a dib image, right?


Paulo Pires

------------------------------
phone  964592113
e-mail  paulopires16@gmail.com
crypt   myPGP public key for encryption emails
<http://kerckhoffs.surfnet.nl/pks/lookup?op=get&search=0x878711213981EEF6>
links    facebook <http://facebook.com/paulopires16> · twitter
<http://twitter.com/#!/paulopires16> · linkedin
<http://www.linkedin.com/pub/paulo-pires/36/4a7/607> · netlog
<http://netlog.com/paulopires16> · javase
<http://download.oracle.com/javase/6/docs/api/> · oracle
<http://www.oracle.com/us/syndication/feeds/index.html>
------------------------------

Aviso Legal:
Esta mensagem de Paulo Pires é destinada exclusivamente ao destinatário.
Pode conter informação confidencial ou legalmente protegida. A incorrecta
transmissão desta mensagem não significa a perda de confidencialidade. Se
esta mensagem for recebida por engano, por favor envie-a de volta para o
remetente e apague-a do seu sistema de imediato. É proibido a qualquer
pessoa que não o destinatário de usar, revelar ou distribuir qualquer parte
desta mensagem.

Disclaimer:
This message from Paulo Pires is destined exclusively to the intended
receiver. It may contain confidential or legally protected information. The
incorrect transmission of this message does not mean the loss of its
confidentiality. If this message is received by mistake, please send it
back to the sender and delete it from your system immediately. It is
forbidden to any person who is not the intended receiver to use, distribute
or copy any part of this message.

2018-03-26 22:58 GMT+01:00 Philippe Lagadec <notifications@github.com>:

**Comment by KatSick** [comment]
@paulopires16 do you manage to parse from Picture DIB files into some images? I have exact same issue from my accdb ole objects
