### ISSUE TITLE
oledir: add more known-bad CLSIDs

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#290]
source: https://github.com/docbleach/DocBleach/issues/23

and https://blog.talosintelligence.com/2017/03/how-malformed-rtf-defeats-security.html

**Comment by ShiaoQu17** [comment]
I checked these CLSIDs in the registry, and some of them were wrong or inappropriate. The modules related to these CLSIDs are attached below:

"{BDD1F04B-858B-11D1-B16A-00C0F0283628}": "MSCOMCTL.ListViewCtrl (Known Vulnerable)",
"{C74190B6-8589-11d1-B16A-00C0F0283628}": "MSCOMCTL.TreeCtrl (Known Vulnerable)",
"{1EFB6596-857C-11D1-B16A-00C0F0283628}": "MSCOMCTL.TabStrip (Known Vulnerable)",
"{66833FE6-8583-11D1-B16A-00C0F0283628}": "MSCOMCTL.Toolbar (Known Vulnerable)",
"{DD9DA666-8594-11D1-B16A-00C0F0283628}": "MSCOMCTL.ImageComboCtrl (Known Vulnerable)",
"{00000535-0000-0010-8000-00AA006D2EA4}": "ADODB.RecordSet (Known Vulnerable)",
"{0E59F1D5-1FBE-11D0-8FF2-00A0D10038BC}": "MSScriptControl.ScriptControl (Known Vulnerable)",
"{05741520-C4EB-440A-AC3F-9643BBC9F847}": "otkloadr.WRLoader (Known Vulnerable)",
"{A08A033D-1A75-4AB6-A166-EAD02F547959}": "otkloadr.WRAssembly (Known Vulnerable)",
"{4C599241-6926-101B-9992-00000B65C6F9}": "Forms.Image (Known Vulnerable)",
"{44F9A03B-A3EC-4F3B-9364-08E0007F21DF}": "Control.TaskSymbol (Known Vulnerable)"
