### ISSUE TITLE
rtfobj: unknown CLSID: 00020820-0000-0000-C000-000000000046

### ISSUE THREAD

**Issue by oppiman** [decalage2/oletools#298]
[3452675-18.doc.rtf_.zip](https://github.com/decalage2/oletools/files/1959675/3452675-18.doc.rtf_.zip)

embedded Microsoft Excel 2003 Worksheet Biff8 Excel.Sheet.8
oletools 0.53dev8:

**Comment by ShiaoQu17** [comment]
00020820-0000-0000-C000-000000000046

Excel.Sheet.8
Excel.Template.8
