### ISSUE TITLE
rtfobj - support for \\\\[0-9a-f]{2} obfuscation trick

### ISSUE THREAD

**Issue by d34ddr34m3r** [decalage2/oletools#302]
VT sample - https://www.virustotal.com/#/file/2aea4396d0f18275f6a4a596d358d1a933c02f8789bda6782094dd5f308056a7/detection

Obfuscation in this sample makes use of three consecutive \\\\[0-9a-f]{2} which is equivalent to a single hexbyte

`52\\00\\00\\006f\\00\\00\\006f\\00\\00\\0074\\00\\00\\002\\00\\00\\00045\\00\\00\\006e\\00\\00\\0074\\00\\00\\0072\\00\\00\\0079\\00\\00\\00\\00\\00\\00\\00\\00\\00`

Current version of rtfobj converts the hexstrings into:
```
000004c5h: 52 00 00 00 6F 00 00 00 6F 00 00 00 74 00 00 00 ; R...o...o...t...
000004d5h: 20 00 00 00 45 00 00 00 6E 00 00 00 74 00 00 00 ;  ...E...n...t...
000004e5h: 72 00 00 00 79 00 00 00 00 00 00                ; r...y......
```

instead of:
```
00000400h: 52 00 6F 00 6F 00 74 00 20 00 45 00 6E 00 74 00 ; R.o.o.t. .E.n.t.
00000410h: 72 00 79 00 00 00 00 00 00 00 00 00 00 00 00 00 ; r.y.............
```

extracted ole object is fragmented though, and will have to be repaired and defragmented (using OffVis) to properly parse the streams.

**Comment by ShiaoQu17** [comment]
I don't think this is an obfuscation trick. It's a mistake I think. 

```
Breakpoint 0 hit
ole32!OleConvertOLESTREAMToIStorage:
772a3952 8bff            mov     edi,edi
0:000:x86> .writemem C:\1.bin poi(poi(poi(esp+0x4)+0x8)) L dwo(poi(esp+0x4)+0xC)
Writing 198c bytes....
```

I set a breakpoint at OleConvertOLESTREAMToIStorage, and Word extracts the same data as what rtfobj extracted.

**Comment by ShiaoQu17** [comment]
https://app.any.run/tasks/f3c0cb26-80b6-4b8b-b198-08305cb5f755

And it didn't trigger.

**Comment by d34ddr34m3r** [comment]
Thank you for checking, ran it through debugger and confirmed you're right about it being a mistake. 
Closing the issue.
