### ISSUE TITLE
rtfobj does not correctly extract object from malicious document

### ISSUE THREAD

**Issue by huettenhain** [decalage2/oletools#307]
First of all, thanks for the great tools. There is a malicious RTF document with the following hash, which causes `rtfobj.py` some problems:
```
37151e8a52ac6b3d01df973f4c35cdfc69a184cbb98ea4a1b798d3cd5b0c9a2d
```
It contains a malicious executable with the following sha256 hash:
```
9f60c8f06de28379e7ad81a4f618cadcd6061dab5cd85f3f9865984f668d210a
```
which can also be seen in [a run on hybrid analysis](https://www.hybrid-analysis.com/sample/37151e8a52ac6b3d01df973f4c35cdfc69a184cbb98ea4a1b798d3cd5b0c9a2d?environmentId=100), the file is extracted as `~bin.tm`. 

It seems that the problem is [trick #4](https://www.decalage.info/rtf_tricks#Trick_4:_Dummy_RTF_Control_Words_Within_the_Hex-encoded_Data) that you have already described on your website. I have crudely modified `rtfobj.py` to account for this with 2 lines of code: https://github.com/huettenhain/oletools/commit/be7af365dd18dabd9a45301207ff6111df992e41

However, neither is my understanding of the RTF format good enough nor do I have a large enough collection of test files to make sure that this change would be a reasonable pull request. If it is, let me know and I will submit it - otherwise, consider this a bug report ;-).

**Comment by decalage2** [comment]
This is related to issue #303,  I'll fix it soon.
