### ISSUE TITLE
can't detect office powerpoint 2003 encrypted file

### ISSUE THREAD

**Issue by sujiacong** [decalage2/oletools#341]
**Affected tool:**
oleid

**Describe the bug**
oleid can not detect  encrypted powerpoint ppt file

**File/Malware sample to reproduce the bug**

**How To Reproduce the bug**
1、use microsoft Office2007 to create a encrypted powerpoint file and save as 2003 format ppt.
2、use oleid detect it

*Expected behavior**
oleid should recognize encrypted file

**Console output / Screenshots**
![ppt_oleid_encypted_failed](https://user-images.githubusercontent.com/22270812/44127167-afc2f238-a06e-11e8-9fd6-628e958ec3b7.jpg)

**Version information:**
 - OS:Linux
 - OS version: ubuntu 16.04
 - Python version: Python 3.5.2
 - oletools version: oleid 0.53

**Comment by dsas** [comment]
Looking at the oletools code and [MSDN documentation](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-ppt/b0963334-4408-4621-879a-ef9c54551fd8) It appears that htis might need special casing.

**Comment by decalage2** [comment]
A solution could be to use msoffcrypto-tool, which seems to detect PPT encryption: https://github.com/nolze/msoffcrypto-tool/blob/master/msoffcrypto/format/ppt97.py

**Comment by decalage2** [comment]
This was actually fixed in oletools 0.54, in PR  #403.
