### ISSUE TITLE
rtfobj: bug when importing log_helper

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#359]
**Affected tool:**
rtfobj

**Describe the bug**
see https://twitter.com/James_inthe_box/status/1055557544272322560

**Console output / Screenshots**
![image](https://user-images.githubusercontent.com/5989656/47605791-68a5ec80-da0b-11e8-927f-ab20d06864fa.png)

**Version information:**
 - OS: Linux
 - Python version: 2.7
 - oletools version: 0.54.dev2

**Comment by decalage2** [comment]
the bug was due to setup.py that did not include the new package oletools.common.log_helper.

**Comment by decalage2** [comment]
Fixed by commit 34d4e60a281f3afd349144e9d084cd5054df7bf7

**Comment by christian-intra2net** [comment]
Oops, sorry!
