### ISSUE TITLE
Avoid unicode errors in non-unicode environment 

### ISSUE THREAD

**Issue by christian-intra2net** [decalage2/oletools#361]
There is a general problem with unicode output, not only with python. The interpreter needs to know how to encode unicode for the shell (or pipe or socket) to handle output. When running in a well-behaved environment, sys.stdout.encoding is something like 'UTF8' which allows print() to convert unicode without problems.

However, when redirecting output to files or when running python scripts in a minimal environment (e.g. in linux with LANG=C), then print()ing unicode fails since python assumes that it can only encode using ASCII, so every attempt to print non-ascii characters fails with a UnicodeError.

A simple demonstration on linux command line:
`python -c "print(u'\u2713')"` succeeds while `LANG=C python -c "print(u'\u2713')"` fails as well as `python -c "print(u'\u2713')" > test.txt` or `python -c "print(u'\u2713')" | wc`.

The problem is also described in [this stackoverflow issue](https://stackoverflow.com/q/27347772/4405656) and in [this interesting article](https://pythonhosted.org/kitchen/unicode-frustrations.html#frustration-3-inconsistent-treatment-of-output) referred to in one of the answers.

The problem could be fixed with a short check to be run at the start of every script (could be moved to a common function). The code can be found in the [first answer to the above issue](https://stackoverflow.com/a/27347906/4405656). The second reference suggests using the python module [kitchen](https://pythonhosted.org/kitchen/), which allows to solve the issue even for stderr where things appear to be even more complicated.

I am happy to implement both, what do you prefer?

**Comment by decalage2** [comment]
Handling unicode issues has always been frustrating with Python... Not sure what the best approach is. I would like to avoid dependencies like kitchen, if it's just to address rare cases. But if it's a practical solution that works in real-life, why not.

**Comment by decalage2** [comment]
@christian-intra2net, is this issue closed now that #365 is merged?

**Comment by christian-intra2net** [comment]
Yes. Thanks for merging!
