### ISSUE TITLE
clsid: unknown CLSID: 978C9E23-D4B0-11CE-BF2D-00AA003F40D0

### ISSUE THREAD

**Issue by bartblaze** [decalage2/oletools#368]
Add the following unknown CLSID, found in an RTF doc:

* CLSID: {978C9E23-D4B0-11CE-BF2D-00AA003F40D0}
* Class name: Forms.Label.1

Looks like an OLE control form (Microsoft Forms 2.0 Label). 

While searching for this specific CLSID, I encountered the following page:
https://github.com/davestewart/maxscript/blob/master/3D/3ds2ae/03_3ds/dev/interface/ax%20property%20grids/axcontrols.ms

Quite some more there, could be useful.

**Comment by mint177** [comment]
[GUID List.txt](https://github.com/decalage2/oletools/files/2619727/GUID.List.txt)

@decalage2 @bartblaze for reference

**Comment by decalage2** [comment]
@mint177, where does the GUID list come from? Usually I use https://uuid.pirate-server.com/

**Comment by decalage2** [comment]
For this CLSID, it's https://uuid.pirate-server.com/978C9E23-D4B0-11CE-BF2D-00AA003F40D0

**Comment by decalage2** [comment]
Looks like https://misc.daniel-marschall.de/projects/guid_analysis/guid.txt

**Comment by mint177** [comment]
> Looks like https://misc.daniel-marschall.de/projects/guid_analysis/guid.txt

Yeah……he extracted this list from the registry. Just for a reference, no need to add them all.
