### ISSUE TITLE
clsid: unknown CLSID: 0002FFFF-0000-CE02-0200-00000000C000

### ISSUE THREAD

**Issue by Kuzuto** [decalage2/oletools#384]
File: 'New Order.doc' - size: 149063 bytes
---+----------+---------------------------------------------------------------
id |index     |OLE Object                                                     
---+----------+---------------------------------------------------------------
0  |000130E9h |Not a well-formed OLE object                                   
---+----------+---------------------------------------------------------------
1  |000170F1h |Not a well-formed OLE object                                   
---+----------+---------------------------------------------------------------
2  |0001F4FAh |format_id: 2 (Embedded)                                        
   |          |class name: 'Equation.3'                                       
   |          |data size: 3072                                                
   |          |CLSID: 0002FFFF-0000-CE02-0200-00000000C000                    
   |          |unknown CLSID (please report at                                
   |          |https://github.com/decalage2/oletools/issues)                  
---+----------+---------------------------------------------------------------

https://www.hybrid-analysis.com/sample/89fe5389b465eab3c16a92166bcab9d70531b8464c618de9743f1075524839ec
https://cape.contextis.com/analysis/30812/
https://www.virustotal.com/#/file/89fe5389b465eab3c16a92166bcab9d70531b8464c618de9743f1075524839ec/detection

**Comment by securitykitten** [comment]
Just took a look at the extracted objects and it looks like it does have the equation editor clsid ("\x02\xce\x02\x00\x00\x00\x00\x00\xc0\x00\x00\x00\x00\x00\x00\x46")  So this may be a bug in traversing the extracted object.

![image](https://user-images.githubusercontent.com/5833122/51686876-49ddd480-1fbf-11e9-92e1-01be86f977bf.png)

**Comment by Kuzuto** [comment]
I can see in my log other files with same CLSID gets detected. So you are right. Something is wrong with the file. I’m closing this.

**Comment by decalage2** [comment]
For me it works fine with the latest dev version of rtfobj:

![image](https://user-images.githubusercontent.com/5989656/51708833-336a6400-2025-11e9-9790-d702579065ea.png)
