### ISSUE TITLE
Source code archive v0.54.tar.gz without colorclass

### ISSUE THREAD

**Issue by jm-edard** [decalage2/oletools#423]
**Affected tool:**
All, 0.54 package

**Describe the bug**
Could you add , like on 0.53.1package, all the module class on package 0.54 please ?

Traceback (most recent call last):
  File "./mraptor.py", line 86, in <module>
    from oletools.thirdparty.tablestream import tablestream
  File "/usr/local/src/oletools-0.54/oletools/thirdparty/tablestream/tablestream.py", line 75, i                                                                                                      n <module>
    import colorclass
ImportError: No module named colorclass

**How To Reproduce the bug**
Juste dowload the package directly.

**Version information:**
 - OS: Debian
 - OS version: 9.8 64 bits
 - Python version: 2.7-13-2
 - oletools version: 0.54

**Comment by decalage2** [comment]
colorclass is now a dependency, it must be installed on its own. The best way to install oletools is to use pip: it automatically downloads and installs all the necessary dependencies for you. See https://github.com/decalage2/oletools/wiki/Install for the instructions.
