### ISSUE TITLE
Olevba - Windows explorer search handler

### ISSUE THREAD

**Issue by otofoto** [decalage2/oletools#440]
Is it possible to register olevba as windows search handler so to do full text search in embedded vba sources? The main use would to be search for used VBA functions in multiple files.

**Comment by decalage2** [comment]
Maybe - do you know how to implement a search handler in Python?

However, I'm not sure it's the best way to go. You can always use olevba to run on multiple files at once (using wildcards) and extract the VBA code in one go, for example:
```
olevba --code --detailed "*"
```

**Comment by otofoto** [comment]
thanks, this suits also.

**Comment by decalage2** [comment]
Moreover, using a search handler means that windows would access the source code of malicious vba macros, and this is likely to trigger antivirus alerts... I don't think it would work well in practice.

**Comment by otofoto** [comment]
I would use it for searching and indexing my own code.

**Comment by decalage2** [comment]
OK I see. I did some searches, but for now I haven't found any solution to implement an iFilter in Python. The only example I've seen is this demo using pywin32 to call existing iFilters: https://github.com/mhammond/pywin32/blob/master/com/win32comext/ifilter/demo/filterDemo.py

**Comment by otofoto** [comment]
It seems it is out of scope for this project but would be nice to have. Especially it is needed for the Microstation mvba macros as they are in separate ole(.mvba) files and hard to manage the code as requires to load each project or export source to text to be able to search. Have not found iFilter for ole either.
