### ISSUE TITLE
Add extensions to list of CLSIDs

### ISSUE THREAD

**Issue by jorangreef** [decalage2/oletools#445]
It would be useful to know the extension associated with a particular CLSID, especially for MS Office files.

e.g. Whether {f4754c9b-64f5-4b40-8af4-679732ac0607} is ".doc" or ".docx".

Is there a mapping somewhere of CLSIDs to extensions, especially for MS Office files? Any references you can point me to?

This would help to cross-check compound file binary signatures with extensions, especially for purposes of antivirus scanning.

**Comment by decalage2** [comment]
I don't know is such a mapping exists (CLSID to file extensions), but it should not be too difficult to build, as there are not so many CLSIDs matching OLE file formats.

**Comment by decalage2** [comment]
...but there may be a better solution: I've been working on a new tool/library, that will be released as part of oletools in the near future. Its purpose is to identify the actual type of a file, based on relevant indicators: CLSID for OLE files, root XML namespace for XML and OpenXML files, etc. Then you get the corresponding file type information, including the expected file extensions. That would address your issue in a broader way than just checking CLSIDs, I guess.

**Comment by jorangreef** [comment]
Thanks, that would be great.
