### ISSUE TITLE
plugin_biff: update to 0.0.17

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#605]
see https://github.com/DidierStevens/DidierStevensSuite/blob/master/plugin_biff.py

**Comment by jloehel** [comment]
@decalage2 Can I work on this one?

**Comment by decalage2** [comment]
Sure, you can submit a PR. Each time I update plugin_biff, I insert the following lines at the beginning to make it work:
```
# Modifications for olevba:
import sys
import binascii
from .oledump_extract import *
# end modifications
```

**Comment by jloehel** [comment]
> Sure, you can submit a PR. Each time I update plugin_biff, I insert the following lines at the beginning to make it work:
> 
> ```
> # Modifications for olevba:
> import sys
> import binascii
> from .oledump_extract import *
> # end modifications
> ```

Thanks, I will open a PR soon. :-)
