### ISSUE TITLE
Oleobj.py BLACKLISTED_RELATIONSHIP_TYPES list of items are not correctly/syntactically separated with comma(,)

### ISSUE THREAD

**Issue by ghanashyams** [decalage2/oletools#641]
**Affected tool:**
oleobj

**Describe the bug**
Seems syntax bug in BLACKLISTED_RELATIONSHIP_TYPES list of items.  'externalReference' and 
    'frame' are not comma(,) separated.

**File/Malware sample to reproduce the bug**
BLACKLISTED_RELATIONSHIP_TYPES = [
    'attachedTemplate',
    'externalLink',
    'externalLinkPath',
    'externalReference'
    'frame'
    'hyperlink',
    'officeDocument',
    'oleObject',
    'package',
    'slideUpdateUrl',
    'slideMaster',
    'slide',
    'slideUpdateInfo',
    'subDocument',
    'worksheet'
]

**How To Reproduce the bug**
Seems syntax bug in BLACKLISTED_RELATIONSHIP_TYPES list of items.  'externalReference' and 
    'frame' are not comma(,) separated.

**Expected behavior**
Seems syntax bug in BLACKLISTED_RELATIONSHIP_TYPES list of items.  'externalReference' and 
    'frame' are not comma(,) separated. 
**Console output / Screenshots**
Use the option "-l debug" to add debugging information, if possible.

**Version information:**
 - OS: Windows/Linux/Mac/Other
 - OS version: x.xx - 32/64 bits
 - Python version: 2.7/3.6 - 32/64 bits
 - oletools version: .56

**Additional context**

**Comment by decalage2** [comment]
Fixed by PR #670.
