### ISSUE TITLE
Differentiate between file based template injection and remote URL based template injection

### ISSUE THREAD

**Issue by scandox** [decalage2/oletools#663]
We've seen a lot of false positives with template injection. It appears it is quite common to have a file:/// based dotm connected to a word document, without malicious intent. At present if `template_injection_found` is set, we cannot tell whether this is looking for a local resource, a LAN resource or a remote URL source.

Also at present it isn't crystal clear (except from code) if it is safe to assume that when an OLE Macro is found, that `template_injection_found` will be false. In other words that we can say well Macros were detected, but none were OLE.

It might make sense to distinguish the target type in some way for these. Also it might make sense to have a flag or property that unambiguously stated no macros were found inside the actual document itself. I know there may be reasons not to do so :)

For now we're reading the results of `extract_vba_macros` and making our own distinction between types of template_injection.

**Comment by decalage2** [comment]
@scandox why did you close the issue? It looks like a legitimate question.

**Comment by scandox** [comment]
@decalage2 Sorry I just felt perhaps I hadn't done enough thinking about it. It takes a fair bit of time to understand the existing code and make a really good suggestion and I thought I hadn't done enough on that. Shall I reopen?
