### ISSUE TITLE
Unable to detect macro

### ISSUE THREAD

**Issue by aoshiken** [decalage2/oletools#697]
**Affected tool:**
olevba, mraptor

**Describe the bug**
The tools are unable to detect a very simple macro embedded in a docm file, the macro is named `Alfredo`

**File/Malware sample to reproduce the bug**
Find attached a password protected zip file with the docm document. The password is "noninfected", anyway the macro is harmless (see its code in the **Expected behaviour** section).

[test.zip](https://github.com/decalage2/oletools/files/6664060/test.zip)

**How To Reproduce the bug**
See the console output on section below

**Console output / Screenshots**
```
$ olevba  -d -l debug ../test-office/test.docm
olevba 0.60 on Python 3.7.3 - http://decalage.info/python/oletools
DEBUG    ftguess: file type=MS Word 2007+ Macro-Enabled Document - container=OpenXML
INFO     Opening ZIP/OpenXML file ../test-office/test.docm
DEBUG    OpenXML subfile [Content_Types].xml
DEBUG    OpenXML subfile _rels/.rels
DEBUG    OpenXML subfile word/_rels/document.xml.rels
DEBUG    OpenXML subfile word/document.xml
DEBUG    OpenXML subfile word/theme/theme1.xml
DEBUG    OpenXML subfile word/settings.xml
DEBUG    OpenXML subfile word/fontTable.xml
DEBUG    OpenXML subfile word/webSettings.xml
DEBUG    OpenXML subfile docProps/app.xml
DEBUG    OpenXML subfile docProps/core.xml
DEBUG    OpenXML subfile word/styles.xml
===============================================================================
FILE: ../test-office/test.docm
Type: OpenXML
DEBUG    detect vba macros
DEBUG    detect xlm macros
No VBA or XLM macros found.

DEBUG    Checking for encryption (normal)
DEBUG    is_encrypted
DEBUG    Checking for encryption using msoffcrypto
DEBUG    no encryption detected
DEBUG    will exit now with code 0
```

```
$ mraptor -l debug ../test-office/test.docm
MacroRaptor 0.56.2 - http://decalage.info/python/oletools
This is work in progress, please report issues at https://github.com/decalage2/oletools/issues
----------+-----+----+--------------------------------------------------------
Result    |Flags|Type|File
----------+-----+----+--------------------------------------------------------
No Macro  |     |OpX:|../test-office/test.docm

Flags: A=AutoExec, W=Write, X=Execute
Exit code: 0 - No Macro
```
**Expected behavior**
Show the detected macro `Alfredo` and its corresponding code:
```
Sub Alfredo()
    MsgBox ("HOLA DESDE LA MACRO DE WORD")
End Sub
```
**Version information:**
 - OS: Linux
 - OS version: 64 bits
 - Python version: 3.7.3 64 bits
 - oletools version: 0.60, the latest PyPi version as of today (16th June)

**Additional context**
The Word document has been created with Microsoft Office Professional Plus 2016 64bits, exactly with Microsoft Word 2016 MSO (16.0..4266.1001) 64bits.

The macro is attached to a small label with the text `Display`, the macro is executed when making a double-click on the label showing a popup with the words `HOLA DESDE LA MACRO DE WORD`.

**Comment by aoshiken** [comment]
Tested with the master branch (latest commit 465e8ed2b2c57a24677eebae90cf57808ac5ae0f) with same results

**Comment by decalage2** [comment]
Hi @aoshiken I opened the file in Word, I see the button with label "display", but I do not see any macro linked to it (no macro code when opening the VBA editor with Alt+F11). And Word does not warn about macros either (no "Enable Content" button).
How do you see the macro code in Word, and how do you run it?

**Comment by aoshiken** [comment]
It was my fault, let me take a look in a  few minutes, I will reopen if necessary

**Comment by decalage2** [comment]
OK, from what I read, when you insert a MACROBUTTON field in Word, you can add the name of a VBA macro that will run if you double-click the field. But that macro needs to exist in the document. In your file, the field points to "Alfredo" (`{MACROBUTTON Alfredo Display}`, but there is no VBA macro with that name.
