### ISSUE TITLE
Version 0.60 tag and changelog

### ISSUE THREAD

**Issue by sebix** [decalage2/oletools#698]
I few weeks ago the version 0.60 has been released. I'm packaging the software for openSUSE and I since am unable to find the changelog for the version. Neither https://www.decalage.info/python/oletools nor github (release, files in the repo) contain a list of changes. Also, the tag/release seems to be missing.

**Comment by decalage2** [comment]
Thanks for reporting this, indeed I forgot to add a tag/release in Github. Will do it shortly.
The changelog is in the wiki here, this one is up-to-date: https://github.com/decalage2/oletools/wiki/Changelog

**Comment by decalage2** [comment]
Here is the release for v0.60: https://github.com/decalage2/oletools/releases/tag/v0.60
