### ISSUE TITLE
olevba: error in _extract_vba

### ISSUE THREAD

**Issue by decalage2** [decalage2/oletools#701]
See https://twitter.com/James_inthe_box/status/1412401873395482629

![image](https://user-images.githubusercontent.com/5989656/124673040-73052d80-deb8-11eb-88c9-31b97a122978.png)

sample: https://app.any.run/tasks/c9e4af38-78b5-40db-846b-c767401d77f9/
https://tria.ge/210706-nlemx52pc6

**Comment by vk3il** [comment]
Just checking in on whether there's an ETA for a fix here? It's broken a very useful downstream tool git-xl that provides a diff for excel VBA code. It looks like it's closely related to or the same as issue #700 where @mikes-gh has proposed a temporary fix. Thanks for your work on this clearly useful library.

**Comment by decalage2** [comment]
Fixed by PR #723
