### ISSUE TITLE
oledir.py  ImportError: cannot import name colorclass

### ISSUE THREAD

**Issue by gasgas4** [decalage2/oletools#77]
running error: 

  ziv$ python oledir.py
Traceback (most recent call last):
  File "oledir.py", line 60, in <module>
    from thirdparty.colorclass import colorclass
ImportError: cannot import name colorclass

Fix this maybe?  
    from thirdparty.colorclass import color

**Comment by decalage2** [comment]
Fixed in commit 51567c7861de4186cf6076b46776a4ca8e62fb03.

This was the same issue as #57 with tablestream, due to a change in the colorclass package.
