### ISSUE TITLE
rtfobj  RuntimeError: Should not have reached this point - index=517F6h

### ISSUE THREAD

**Issue by gasgas4** [decalage2/oletools#78]
running: 
  python rtfobj.py  /tmp/a/dbb2685f9c80473bc0c273c98a282de38fad12e0f2b74b811cfdcb701b4ea559

Error tracing: 
rtfobj 0.50 - http://decalage.info/python/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues

===============================================================================
File: '/tmp/a/dbb2685f9c80473bc0c273c98a282de38fad12e0f2b74b811cfdcb701b4ea559' - size: 937427 bytes
---+----------+-------------------------------+-------------------------------
id |index     |OLE Object                     |OLE Package
---+----------+-------------------------------+-------------------------------
Traceback (most recent call last):
  File "rtfobj.py", line 795, in <module>
    main()
  File "rtfobj.py", line 791, in main
    save_object=options.save_object)
  File "rtfobj.py", line 641, in process_file
    rtfp.parse()
  File "rtfobj.py", line 357, in parse
    raise RuntimeError('Should not have reached this point - index=%Xh' % self.index)
RuntimeError: Should not have reached this point - index=517F6h

**Comment by decalage2** [comment]
Thank you for reporting this parsing issue, it was triggered by many samples. Now the parser should work much better.

Fixed by commit f4bb562c19054835268d3ac85a75c1aa3362519f.
