### ISSUE TITLE
Parse Additional String Functions

### ISSUE THREAD

**Issue by resech** [decalage2/oletools#94]
Hello, I was curious if there were roadmap items to support some additional string functions for deobfuscation in olevba? I've encountered left, right, mid and case changes (lcase, ucase) quite frequently but I'm doubting that's a complete list. Thank you.

**Comment by decalage2** [comment]
Good point. Olevba can only parse and deobfuscate constant expressions (i.e. without variables), so it only works in specific cases. Would that address your question?

If the macro uses expressions with variables, or builds strings in several stages, then another solution is VBA emulation using [ViperMonkey](https://github.com/decalage2/ViperMonkey).

**Comment by resech** [comment]
I'd missed ViperMonkey when I had opened this issue, that will probably do the trick.
